### ISSUE TITLE
Remove box-sizing: content-box;

### ISSUE THREAD

**Issue by asika32764** [asika32764/joomla-bootstrap3-isis-template#1]
In template.less

``` css
.chzn-container-active .chzn-drop {
    box-sizing: content-box;
}
```
